//const images_path = "http://localhost:3000/assets/gallery/700px/";
const images_path = "http://localhost:5173/dev/assets/";


 const stock = [
	{img: images_path+"p-1.jpg", alt: "", aspect: {h:2, w:3} },
	{img: images_path+"p-2.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-3.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-4.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-5.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-6.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-7.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-8.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-9.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-10.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-11.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-12.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-13.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-14.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-15.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-16.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-17.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-18.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-19.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-20.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-21.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-22.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-23.jpg", alt: "", aspect: {h:3, w:2}},
]


const wedding = [
	{img: images_path+"p-1.jpg", alt: "", aspect: {h:2, w:3} },
	{img: images_path+"p-2.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-3.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-4.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-5.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-6.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-16.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-7.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-8.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-9.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-10.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-11.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-12.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-22.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-13.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-14.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-15.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-20.jpg", alt: "", aspect: {h:3, w:2}},
	{img: images_path+"p-17.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-18.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-19.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-21.jpg", alt: "", aspect: {h:2, w:3}},
	{img: images_path+"p-23.jpg", alt: "", aspect: {h:2, w:3}},
]

 const wild_stock = [
	{img: images_path+"p-1.jpg" },
	{img: images_path+"p-2.jpg"},
	{img: images_path+"p-3.jpg"},
	{img: images_path+"p-4.jpg"},
	{img: images_path+"p-5.jpg"},
	{img: images_path+"p-6.jpg"},
	{img: images_path+"p-7.jpg"},
	{img: images_path+"p-8.jpg"},
	{img: images_path+"p-9.jpg"},
	{img: images_path+"p-10.jpg"},
	{img: images_path+"p-11.jpg"},
	{img: images_path+"p-12.jpg"},
	{img: images_path+"p-13.jpg"},
	{img: images_path+"p-14.jpg"},
	{img: images_path+"p-15.jpg"},
	{img: images_path+"p-16.jpg"},
	{img: images_path+"p-17.jpg"},
	{img: images_path+"p-18.jpg"},
	{img: images_path+"p-19.jpg"},
	{img: images_path+"p-20.jpg"},
	{img: images_path+"p-21.jpg"},
	{img: images_path+"p-22.jpg"},
	{img: images_path+"p-23.jpg"},
]

 const simple_stock = [
	images_path+"p-1.jpg",
	images_path+"p-2.jpg",
	images_path+"p-3.jpg",
	images_path+"p-4.jpg",
	images_path+"p-5.jpg",
	images_path+"p-6.jpg",
	images_path+"p-7.jpg",
	images_path+"p-8.jpg",
	images_path+"p-9.jpg",
	images_path+"p-10.jpg",
	images_path+"p-11.jpg",
	images_path+"p-12.jpg",
	images_path+"p-13.jpg",
	images_path+"p-14.jpg",
	images_path+"p-15.jpg",
	images_path+"p-16.jpg",
	images_path+"p-17.jpg",
	images_path+"p-18.jpg",
	images_path+"p-19.jpg",
	images_path+"p-20.jpg",
	images_path+"p-21.jpg",
	images_path+"p-22.jpg",
	images_path+"p-23.jpg",
]


 export default {normal: stock, wild: wild_stock, wilder: simple_stock}
